language: php

sudo: false

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install: composer self-update

install: 
  - if [[ $TRAVIS_PHP_VERSION = 5.4 ]]; then composer update; fi;
  - composer install

script: vendor/bin/phpunit
